setup_singlept_run: Print errors to stderr.

diff --git a/job_scripts/setup_singlept_run b/job_scripts/setup_singlept_run
--- a/job_scripts/setup_singlept_run
+++ b/job_scripts/setup_singlept_run
@@ -76,7 +76,7 @@ while [ $# -gt 0 ]; do
   case "$1" in
     -c|--case-dir)
       if [ $# -lt 2 ]; then
-        echo "ERROR: $1 requires an argument"
+        echo "ERROR: $1 requires an argument" >&2
         exit 1
       fi
       case_dir="$2"
@@ -84,7 +84,7 @@ while [ $# -gt 0 ]; do
       ;;
     -n|--case-name)
       if [ $# -lt 2 ]; then
-        echo "ERROR: $1 requires an argument"
+        echo "ERROR: $1 requires an argument" >&2
         exit 1
       fi
       case_name="$2"
@@ -92,7 +92,7 @@ while [ $# -gt 0 ]; do
       ;;
     -s|--src-dir)
       if [ $# -lt 2 ]; then
-        echo "ERROR: $1 requires an argument"
+        echo "ERROR: $1 requires an argument" >&2
         exit 1
       fi
       src_dir="$2"
@@ -100,7 +100,7 @@ while [ $# -gt 0 ]; do
       ;;
     -u|--user-mods-dir)
       if [ $# -lt 2 ]; then
-        echo "ERROR: $1 requires an argument"
+        echo "ERROR: $1 requires an argument" >&2
         exit 1
       fi
       user_mods_dir="$2"
@@ -115,12 +115,12 @@ while [ $# -gt 0 ]; do
       exit 0
       ;;
     -*)
-      echo "ERROR: unknown option '$1'"
+      echo "ERROR: unknown option '$1'" >&2
       exit 1
       ;;
     *)
       if [ -n "$config_file" ]; then
-        echo "ERROR: unexpected argument '$1'"
+        echo "ERROR: unexpected argument '$1'" >&2
         exit 1
       fi
       config_file="$1"
@@ -130,7 +130,7 @@ while [ $# -gt 0 ]; do
 done
 
 if [ -z "$config_file" ]; then
-  echo "ERROR: please specify config file"
+  echo "ERROR: please specify config file" >&2
   exit 1
 fi
 
@@ -154,7 +154,7 @@ set -u
 
 chargenum="${CHARGENUM:-$PROJECT}"
 if [ -z "${chargenum}" ]; then
-  echo "ERROR: neither CHARGENUM nor PROJECT is set"
+  echo "ERROR: neither CHARGENUM nor PROJECT is set" >&2
   exit 1
 fi
 
@@ -163,14 +163,14 @@ case_name=${CASE_DIR}/${CASENAME}
 
 # change into cime directory
 set +e
-cd "${SRC_DIR}/cime/scripts" || { echo "ERROR: Failed to change directory to ${SRC_DIR}/cime/scripts"; exit 1; }
+cd "${SRC_DIR}/cime/scripts" || { echo "ERROR: Failed to change directory to ${SRC_DIR}/cime/scripts" >&2; exit 1; }
 set -e
 
 # create a new case
 ./create_newcase --case ${case_name} --compset ${COMPSET} --res CLM_USRDAT --project ${chargenum} --run-unsupported --user-mods-dir ${USER_MODS_DIR}
 
 set +e
-cd "${case_name}" || { echo "ERROR: Failed to change directory to ${case_name}"; exit 1; }
+cd "${case_name}" || { echo "ERROR: Failed to change directory to ${case_name}" >&2; exit 1; }
 set -e
 
 # env_workflow.xml
