setup_singlept_run: Add optional -n/--case-name argument.

diff --git a/job_scripts/setup_singlept_run b/job_scripts/setup_singlept_run
--- a/job_scripts/setup_singlept_run
+++ b/job_scripts/setup_singlept_run
@@ -18,11 +18,10 @@ and namelist settings, then runs case.setup, preview_namelists, and
 case.build.
 
 Usage:
-  ./setup_singlept_run [-c|--case-dir <dir>] [-s|--src-dir <dir>] [-u|--user-mods-dir <dir>] <config_file>
+  ./setup_singlept_run [-c|--case-dir <dir>] [-n|--case-name <name>] [-s|--src-dir <dir>] [-u|--user-mods-dir <dir>] <config_file>
 
 The config file is sourced via read_config and must define the following:
 
-  CASENAME       name of the case (case is created at \$CASE_DIR/\$CASENAME).
   COMPSET        compset to use (e.g. I1PtClm60Fates).
   SITE           site identifier; used to locate the subset surface/domain
                  data and the fsurdat file.
@@ -37,6 +36,9 @@ Optional:
   CASE_DIR       directory in which the new case will be created. Can also be
                  set on the command line with -c/--case-dir, which takes
                  precedence over the config file.
+  CASENAME       name of the case (case is created at \$CASE_DIR/\$CASENAME).
+                 Can also be set on the command line with -n/--case-name, which
+                 takes precedence over the config file.
   USER_MODS_DIR  user_mods directory passed to create_newcase. Can also be
                  set on the command line with -u/--user-mods-dir, which takes
                  precedence over the config file. If set in neither place,
@@ -65,6 +67,7 @@ EOM
 
 # parse command-line arguments
 case_dir=""
+case_name=""
 config_file=""
 src_dir=""
 user_mods_dir=""
@@ -76,6 +79,14 @@ while [ $# -gt 0 ]; do
         exit 1
       fi
       case_dir="$2"
+      shift 2
+      ;;
+    -n|--case-name)
+      if [ $# -lt 2 ]; then
+        echo "ERROR: $1 requires an argument"
+        exit 1
+      fi
+      case_name="$2"
       shift 2
       ;;
     -s|--src-dir)
@@ -130,6 +141,7 @@ read_config "$config_file"
 
 # optional arg value precedence: command-line flag > config file > default
 CASE_DIR="${case_dir:-${CASE_DIR}}"
+CASENAME="${case_name:-${CASE_NAME}}"
 SRC_DIR="${src_dir:-${SRC_DIR}}"
 USER_MODS_DIR="${user_mods_dir:-${USER_MODS_DIR:-$DEFAULT_USER_MODS_DIR}}"
 
